name: WorldProtect
main: io.github.digitalmoth.WorldProtect
version: 1.0
author: digitalmoth
permissions:
  worldprotect.modify:
     default: false
     description: Grants access to modify worlds that are noticed in config
  worldprotect.commands:
     default: false
     description: Grants access to execute commands that are noticed in config